name: Tests

on:
  push:
    branches: [ main, php ]
  pull_request:
    branches: [ main, php ]

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php-version }})

    #runs-on: ubuntu-latest
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        #os: [ ubuntu-latest, macos-latest ]
        os: [ubuntu-20.04]
        php-version: [ '8.0', '7.4', '7.3', '7.2', '7.1', '7.0' ]
      max-parallel: 6

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        #run: vendor/bin/phpunit --coverage-text --exclude-group internet
        run: composer run-script test

  PHPUnit-hhvm:
    name: PHPUnit (HHVM)
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: azjezz/setup-hhvm@v1
        with:
          version: lts-3.30
      - run: hhvm $(which composer) require phpunit/phpunit:^5 --dev # requires legacy phpunit

      - name: Run test suite
        run: hhvm vendor/bin/phpunit --exclude-group internet